# Generated by Django 5.1.6 on 2025-02-12 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=3)),
                ('can_give_to', models.ManyToManyField(related_name='can_receive_from', to='dnr_manipulation.bloodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=450)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('medicial_report', models.FileField(upload_to='donor_reports/')),
                ('date_donated', models.DateField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnr_manipulation.bloodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TransfusionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('center_name', models.CharField(max_length=450)),
                ('location', models.CharField(max_length=450)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_available', models.BooleanField(default=True)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnr_manipulation.bloodgroup')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnr_manipulation.donor')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('quantity_ml', models.IntegerField()),
                ('hospital', models.CharField(max_length=450)),
                ('location', models.CharField(max_length=450)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnr_manipulation.bloodgroup')),
                ('approved_at', models.ManyToManyField(blank=True, to='dnr_manipulation.transfusioncenter')),
            ],
        ),
    ]
